aten.any.default and fx converter
ROCm/torch_migraphx pull request #142
Opened 2024-06-25 20:12 UTC by CharlieL7

* Relies on [#3206](https://github.com/ROCm/AMDMIGraphX/pull/3206)
* Converts to bool and then uses `reduce_any` in MIGraphX

2024-07-08 17:24 UTC, shivadbhavsar submitted a review, later dismissed

2024-07-08 17:24 UTC, shivadbhavsar commented
We might have to modify the jenkinsfile for CI to be able to pass these test cases

2024-07-15 23:08 UTC, shivadbhavsar commented on py/torch_migraphx/fx/converters/acc_ops_converters.py
> +@migraphx_converter(acc_ops.any)
Once #158 is merged, you can update this and the other converters here to
```suggestion
@migraphx_converter(acc_ops.any, min_migraphx_ver="2.11.0")
```

2024-07-17 21:58 UTC, shivadbhavsar commented on tests/fx/converters/test_reduce_ops_fx.py
> +                                          ([2, 3], False), (None, None)])
```suggestion

@pytest.mark.skip_min_migraphx_ver("2.11.0")
@pytest.mark.parametrize('dim, keepdim', [(0, True), (-1, False),
                                          ([2, 3], False), (None, None)])
```

With #161 you can add this to skip these tests

2024-07-17 21:58 UTC, shivadbhavsar commented on tests/fx/converters/test_reduce_ops_fx.py
> +                                          ([2, 3], False), (None, None)])
```suggestion

@pytest.mark.skip_min_migraphx_ver("2.11.0")
@pytest.mark.parametrize('dim, keepdim', [(0, True), (-1, False),
                                          ([2, 3], False), (None, None)])
```

2024-07-17 21:58 UTC, shivadbhavsar commented on tests/dynamo/converters/test_reduce_ops_dynamo.py
> +    torch.ops.aten.any.dim,
```suggestion
    pytest.param(torch.ops.aten.all.dim, marks=pytest.mark.skip_min_migraphx_ver("2.11.0")),
    pytest.param(torch.ops.aten.any.dim, marks=pytest.mark.skip_min_migraphx_ver("2.11.0")),
```

2024-07-17 21:58 UTC, shivadbhavsar commented on tests/dynamo/converters/test_reduce_ops_dynamo.py
> +    torch.ops.aten.any.dim,
```suggestion
    pytest.param(torch.ops.aten.all.dim, marks=pytest.mark.skip_min_migraphx_ver("2.11.0")),
    pytest.param(torch.ops.aten.any.dim, marks=pytest.mark.skip_min_migraphx_ver("2.11.0")),
```

2024-07-17 21:58 UTC, shivadbhavsar commented on tests/dynamo/converters/test_reduce_ops_dynamo.py
> +    torch.ops.aten.any.default,
```suggestion
    pytest.param(torch.ops.aten.all.dim, marks=pytest.mark.skip_min_migraphx_ver("2.11.0")),
    pytest.param(torch.ops.aten.any.dim, marks=pytest.mark.skip_min_migraphx_ver("2.11.0")),
```

2024-07-19 18:14 UTC, shivadbhavsar requested changes

2024-07-19 18:14 UTC, shivadbhavsar commented on tests/dynamo/converters/test_reduce_ops_dynamo.py
> +    pytest.param(torch.ops.aten.any.dim, marks=pytest.mark.skip_min_migraphx_ver("2.11.0")),
```suggestion
    pytest.param(torch.ops.aten.all.default, marks=pytest.mark.skip_min_migraphx_ver("2.11.0")),
    pytest.param(torch.ops.aten.any.default, marks=pytest.mark.skip_min_migraphx_ver("2.11.0")),
```

2024-07-19 18:14 UTC, shivadbhavsar commented on py/torch_migraphx/fx/tracer/acc_tracer/acc_ops.py
> +    return reduce_op_mapper(node, mod, any)
Turns out that the torch documentation is incorrect, the dim parameter for any and all doesnt actually take a tuple of ints (it only takes an int). So you dont want to use the reduce_op_mapper (which converts dim to a tuple). You can add a flag to reduce_op_mapper to not do this conversion or just use a simple register_acc_op_mapping instead. Whatever you find easier.

2024-07-19 18:14 UTC, shivadbhavsar commented on py/torch_migraphx/fx/tracer/acc_tracer/acc_ops.py
> +    return input.all(dtype=dtype)
```suggestion
    return input.all()
```
all doesnt take dtype param

2024-07-19 18:16 UTC, shivadbhavsar commented on tests/fx/converters/test_reduce_ops_fx.py
> +                                          ([2, 3], False), (None, None)])
remove the multiple dim test case, torch op doesnt support it

2024-07-19 18:16 UTC, shivadbhavsar commented on tests/fx/converters/test_reduce_ops_fx.py
> +@pytest.mark.parametrize('dim, keepdim', [(0, True), (-1, False),
remove the multiple dim test case

2024-07-19 18:38 UTC, shivadbhavsar commented on py/torch_migraphx/fx/converters/aten_ops_converters.py
add decorator for torch.ops.aten.any.dim

2024-07-19 18:38 UTC, shivadbhavsar commented on py/torch_migraphx/fx/converters/aten_ops_converters.py
> +
add decorator for torch.ops.aten.all.dim

2024-07-23 20:16 UTC, CharlieL7 commented on py/torch_migraphx/fx/tracer/acc_tracer/acc_ops.py
> +    return reduce_op_mapper(node, mod, any)
How did you figure that out?

2024-07-23 20:26 UTC, CharlieL7 commented on py/torch_migraphx/fx/converters/aten_ops_converters.py
Where are you getting the reference to aten.any.dim?

2024-07-23 22:33 UTC, shivadbhavsar commented on py/torch_migraphx/fx/tracer/acc_tracer/acc_ops.py
> +    return reduce_op_mapper(node, mod, any)
ran the test case locally since CI was overloaded. It complained in some way about that parameter so I just tried `torch.any(x, (0,1))` in a python session. Turns out it expects an int only for dim and errors out otherwise

2024-07-23 22:37 UTC, shivadbhavsar commented
This PR is pointing into `pytest_skip_version` instead of `master` btw

2024-07-23 23:24 UTC, shivadbhavsar commented on py/torch_migraphx/fx/converters/aten_ops_converters.py
https://pytorch.org/docs/stable/torch.compiler_ir.html#:~:text=Tensor%20self)%20%2D%3E%20Tensor-,aten.any.dim,-any.dim(Tensor
That only really says of its existence and not much else unfortunately, but if you run `torch.ops.aten.any.dim()` in an interpreter session, it will blow up and tell you the function signature is `aten::any.dim(Tensor self, int dim, bool keepdim=False) -> Tensor`

2024-07-24 23:34 UTC, CharlieL7 commented
Passes on my local machine with MIGraphX on develop branch

2024-07-25 17:24 UTC, shivadbhavsar commented on tools/install_migraphx.sh
> +MIGRAPHX_BRANCH=${1:-"develop"}
revert this before merging. It defaults to master for QA

2024-07-25 17:24 UTC, shivadbhavsar approved these changes

2024-07-26 16:53 UTC, merged