acc implementation of linalg_vector_norm
ROCm/torch_migraphx pull request #166
Opened 2024-07-22 19:04 UTC by shivadbhavsar

2024-07-26 21:18 UTC, bpickrel requested changes

2024-07-26 21:18 UTC, bpickrel commented on py/torch_migraphx/fx/converters/aten_ops_converters.py
> +    # For dim the aten type is: int[1]? dim=None. Unfold int[1] to scalar
Confusing.  Is  it a typo?

2024-07-26 21:18 UTC, bpickrel commented on py/torch_migraphx/fx/converters/acc_ops_converters.py
> +    ord = kwargs["ord"]
Add support for default value of 2 for ord

2024-07-26 22:36 UTC, shivadbhavsar commented on py/torch_migraphx/fx/converters/acc_ops_converters.py
> +    ord = kwargs["ord"]
2 falls under `sum(abs(x)^{ord})^{(1 / ord)}`
There is a test case for it too

2024-07-26 22:37 UTC, shivadbhavsar commented on tests/fx/converters/test_linalg_ops_fx.py
> +    (2, 1, True),
@bpickrel test case where ord=2

2024-07-26 22:42 UTC, shivadbhavsar commented on py/torch_migraphx/fx/converters/aten_ops_converters.py
> +    # For dim the aten type is: int[1]? dim=None. Unfold int[1] to scalar
nope, this is copy pasted from the function definition python gives when running `torch.ops.aten.linalg_vector_norm.default()` 
Full output:
`RuntimeError: aten::linalg_vector_norm() is missing value for argument 'self'. Declaration: aten::linalg_vector_norm(Tensor self, Scalar ord=2, int[1]? dim=None, bool keepdim=False, *, ScalarType? dtype=None) -> Tensor`

For some reason dim is defined as a int vector with 1 element in the c++ implementation. So ya confusing, agreed

2024-07-26 23:50 UTC, bpickrel commented on tests/fx/converters/test_linalg_ops_fx.py
> +    (2, 1, True),
```suggestion
    (2, 1, True),
    (None, 1, True),
```
I don't think your code will handle that, but it would be only 1 or 2 lines to add it.

2024-07-26 23:51 UTC, bpickrel commented on tests/fx/converters/test_linalg_ops_fx.py
> +    (2, 1, True),
It should default to 2.

2024-07-29 16:45 UTC, shivadbhavsar commented on tests/fx/converters/test_linalg_ops_fx.py
> +    (2, 1, True),
See new test case, I think thats what youre really asking for. Pytorch defaults the value of `ord` to 2 when not given, so the converter still works as expected

2024-07-29 17:13 UTC, bpickrel commented on tests/fx/converters/test_linalg_ops_fx.py
> +    (2, 1, True),
The display of changes by github is getting a bit messy, but what I see is a test case in `fx` where the inputs are `()` and no corresponding case for `dynamo`.  I'm going to assume that's what you intended and call it complete.

2024-07-29 17:14 UTC, bpickrel approved these changes
Leave it up to you whether to change the confusing comment I flagged.  Otherwise, good.

2024-07-29 17:31 UTC, merged

2024-07-29 18:31 UTC, shivadbhavsar commented on tests/fx/converters/test_linalg_ops_fx.py
> +def test_linalg_vector_norm_defaults():
@bpickrel

2024-07-29 18:31 UTC, shivadbhavsar commented on tests/fx/converters/test_linalg_ops_fx.py
> +    (2, 1, True),
Sorry, missed this comment before merging, hope it makes sense though