154 op support atengludefault
ROCm/torch_migraphx pull request #175
Opened 2024-08-21 19:25 UTC by aarushjain29

2024-08-26 14:09 UTC, shivadbhavsar commented on py/torch_migraphx/fx/converters/aten_ops_converters.py
> +@migraphx_converter(torch.ops.aten.glu.default)
missing test for this under test/dynamo/

2024-08-26 14:12 UTC, shivadbhavsar commented on py/torch_migraphx/fx/converters/aten_ops_converters.py
> +    assert len(args) == 2
```suggestion
    assert len(args) >= 1
```

2024-08-26 14:13 UTC, shivadbhavsar commented on tests/fx/converters/test_activations_fx.py
> +
add test case where dim is not provided

2024-10-30 18:28 UTC, shivadbhavsar commented on tests/fx/converters/test_activations_fx.py
> +
This is not resolved. This means your funcmodule should be defined as follows:
`FuncModule(torch.nn.functional.glu)`

You can do this is a seperate function or add a line where dim is None in your parametrize and wrap the above call in if dim == None clause

2024-10-31 18:38 UTC, bpickrel approved these changes
Nothing to add.

2024-10-31 20:00 UTC, shivadbhavsar requested changes
unresolved comment - just marking as requested changes so it doesnt get missed

2024-11-04 18:00 UTC, shivadbhavsar approved these changes

2024-11-04 19:06 UTC, merged