153 op support atenrepeatdefault
ROCm/torch_migraphx pull request #176
Opened 2024-08-28 04:24 UTC by aarushjain29

2024-08-28 20:34 UTC, shivadbhavsar reviewed
Need to add a test case in tests/dynamo/converters/test_shape_ops_dynamo.py

2024-08-28 20:34 UTC, shivadbhavsar commented on py/torch_migraphx/fx/converters/acc_ops_converters.py
> +    inp_shape = list(inp.shape().lens()) if hasattr(inp.shape(), 'lens') else list(inp.shape())
did you run into a case where inp was somehow a `torch.Tensor` object? I think `inp_shape = inp.shape().lens()` should be fine here.

2024-08-28 20:34 UTC, shivadbhavsar commented on tests/fx/converters/test_shape_ops_fx.py
> +        verify_outputs(mod, mgx_mod, inp)
```suggestion
    mod_method = MethodModule('repeat', *repeat_dims)

    mgx_mod = convert_to_mgx(mod_method, [inp])
    verify_outputs(mod_method, mgx_mod, inp)
```
Seems like there is no functional call, its only implemented as a method

2024-08-28 20:34 UTC, shivadbhavsar commented on py/torch_migraphx/fx/converters/aten_ops_converters.py
> +def aten_ops_squeeze(mgx_module, node, args, kwargs):
```suggestion
def aten_ops_repeat(mgx_module, node, args, kwargs):
```

2024-10-30 18:15 UTC, aarushjain29 commented on tests/fx/converters/test_shape_ops_fx.py
> +        verify_outputs(mod, mgx_mod, inp)
There is no torch.repeat(...) functional call, so only need to support the "call_method" case.

2024-10-30 18:45 UTC, shivadbhavsar commented on py/torch_migraphx/fx/tracer/acc_tracer/acc_ops.py
> +
```suggestion
```
format

2024-10-30 18:45 UTC, shivadbhavsar commented on py/torch_migraphx/fx/converters/acc_ops_converters.py
> +    inp_shape = list(inp.shape().lens()) if hasattr(inp.shape(), 'lens') else list(inp.shape())
can you respond to this? If you are seeing something here in kwargs["input"] that is not a migraphx insturction, that is concerning

2024-10-30 18:45 UTC, shivadbhavsar commented on tests/fx/converters/test_shape_ops_fx.py
> +    ((2, 1, 3), (2, 3, 1)),
add a test case here where the repeat_dims are longer than the input size (thats allowed). eg. (2,1,3), (2,1,1,2).

This case should be handled by first unsquezing any missing dimensions in the front of the tensor, and then applying the same logic you already have. Should be a simple enough twek i think. So to be clear the example with `((2,1,3), (2,1,1,2))`, you would first apply an unsqueeze on axis 0. If your repeat dims had 5 values here, then you would have to unsqueze dims 0,1.

2024-10-30 18:52 UTC, shivadbhavsar commented on py/torch_migraphx/fx/converters/acc_ops_converters.py
> +    inp_shape = list(inp.shape().lens()) if hasattr(inp.shape(), 'lens') else list(inp.shape())
nvm, i see its changed

2024-10-31 20:01 UTC, shivadbhavsar requested changes
changing status for clarity

2024-11-04 17:34 UTC, shivadbhavsar approved these changes

2024-11-04 18:18 UTC, merged