torch.nn.functional.scaled_dot_product_attention implementation
ROCm/torch_migraphx pull request #185
Opened 2024-09-04 01:36 UTC by richagadgil

https://pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html#torch-nn-functional-scaled-dot-product-attention

2024-09-05 20:43 UTC, shivadbhavsar commented on tests/fx/converters/test_attn.py
> +        attn_mask = torch.ones(L, S, dtype=torch.bool).cuda()
add a test where the attn_mask isnt bool (case where you just add the values to the attn_bias)

2024-09-05 20:44 UTC, shivadbhavsar commented on py/torch_migraphx/fx/converters/acc_ops_converters.py
> +    scale_factor = 1 / math.sqrt(query.shape().lens()[-1]) if kwargs.get("scale") is None else kwargs["scale"]
```suggestion
    scale_factor = 1 / torch.sqrt(query.shape().lens()[-1]) if kwargs.get("scale") is None else kwargs["scale"]
```

2024-09-05 23:26 UTC, richagadgil commented on tests/fx/converters/test_attn.py
> +        attn_mask = torch.ones(L, S, dtype=torch.bool).cuda()
Done

2024-09-06 02:06 UTC, shivadbhavsar requested changes
seems like pytest is blowing up because both test file names are the same, call one test_attn_fx.py and the other test_attn_dynamo.py like with all the other tests

2024-09-06 17:47 UTC, shivadbhavsar commented on tests/dynamo/converters/test_attn_dynamo.py
> +])
```suggestion
@pytest.mark.parametrize('op_alias', [
    pytest.param(torch.ops.aten._scaled_dot_product_flash_attention.default, marks=pytest.mark.skip_min_torch_ver("2.3")),
])
```

2024-09-09 23:32 UTC, shivadbhavsar approved these changes

2024-09-09 23:32 UTC, merged