Aten roi align
ROCm/torch_migraphx pull request #209
Opened 2024-10-18 20:19 UTC by bpickrel

Add aten and acc converters for the RoiAlign op.

This change is dependent on Migraphx PR [3482](https://github.com/ROCm/AMDMIGraphX/pull/3482).  It can't be tested or merged until that branch is merged.  (Test locally using MigraphX branch `roialign_fix`

As of date of PR creation, the aten converter test `test_roialign_d` is still incomplete.

2024-10-22 19:19 UTC, shivadbhavsar requested changes

2024-10-22 19:19 UTC, shivadbhavsar commented on tools/install_migraphx.sh
> +make -j88 install
revert

2024-10-22 19:19 UTC, shivadbhavsar commented on tests/fx/converters/test_pooling_fx.py
> +    raise RuntimeError("asdfsd ")
remove

2024-10-22 19:19 UTC, shivadbhavsar commented on py/torch_migraphx/fx/converters/aten_ops_converters.py
> +    acc_kwargs["aligned"] = args[6] if len(args) >= 7 else None
```suggestion
```
Aten declaration is: `torchvision::roi_align(Tensor input, Tensor rois, float spatial_scale, SymInt pooled_height, SymInt pooled_width, int sampling_ratio, bool aligned)`. Ie. none of these arguments have default values and so any check with `if len(args) ...` in this case is unnecessary. The functions HAS to be called with each of these args specified

2024-10-22 19:54 UTC, bpickrel commented on tools/install_migraphx.sh
> +make -j88 install
Is there a reason we don't want to use the multithread flag?

2024-10-22 21:03 UTC, shivadbhavsar commented on tools/install_migraphx.sh
> +make -j88 install
Well usually the number you set depends on the system. Also, the rbuild command does the building part here (which i think is multithreaded?), the make install just copies the files over to opt/rocm and so multithreading that doesnt much of a difference

2024-10-23 19:58 UTC, shivadbhavsar requested changes

2024-10-23 19:58 UTC, shivadbhavsar commented on py/torch_migraphx/fx/mgx_module.py
> -
revert

2024-10-23 19:58 UTC, shivadbhavsar commented on py/torch_migraphx/fx/converters/acc_ops_converters.py
> +        # This isn't supported at this time because torchvision roi_align.default() doesn't support it
Clean up debug comments. Also can we change the isnt supported comment to a `TODO` comment. Its not supported at this time because we are having trouble consuming a list input in the test cases atm. "torchvision roi_align.default() doesn't support it" is not a valid reason not to support it in the acc converter.

2024-10-23 19:58 UTC, shivadbhavsar commented on py/torch_migraphx/fx/tracer/acc_tracer/acc_ops.py
> +import torchvision
```suggestion
try:
    import torchvision
except ImportError:
    pass
```
This is not a mandatory prerequisite for torch_migraphx so wrap it in a try/except

2024-10-23 19:58 UTC, shivadbhavsar commented on py/torch_migraphx/fx/tracer/acc_tracer/acc_ops.py
> +@register_acc_op_mapping(
```suggestion
if 'torchvision' in sys.modules:
    @register_acc_op_mapping(
```
wrap the roi_align function definition in this if so that it doesnt blow up if torchvision isnt installed

2024-10-23 19:58 UTC, shivadbhavsar commented on tests/fx/converters/test_pooling_fx.py
> +def test_roialign(input, boxes, output_size, spatial_scale, sampling_ratio, aligned):
can you move this to `test_torchvision_models_fx.py` and follow the example there to skip if torchvision is not installed

2024-10-23 19:58 UTC, shivadbhavsar commented on tests/dynamo/converters/test_pooling_dynamo.py
> +def test_roialign(op_alias, input, boxes, output_size, spatial_scale, sampling_ratio, aligned):
Similar to the fx test comment, this should be in a `test_torchvision_models_dynamo.py` file, and it should mark to skip in the same way if torchvision is not installed.

2024-10-23 20:06 UTC, shivadbhavsar commented on py/torch_migraphx/fx/converters/acc_ops_converters.py
> +        # This isn't supported because torchvision roi_align.default() doesn't support it
I am not sure what you mean, this is the case where the rois are a list of tensors right? Thats not even supported by the aten op. This is only for the acc op case where the rois are defined as a list

On a second look, that if statement does not work at all, if the rois are defined as a list, your boxes_ref variable wont be a migraphx instruction and the .shape call isnt valid anyways

2024-10-23 23:07 UTC, bpickrel commented on py/torch_migraphx/fx/converters/acc_ops_converters.py
> +        # This isn't supported because torchvision roi_align.default() doesn't support it
It does work as an instruction; I tested it that far before I decided to drop it.   I'd have to clean up the acc_ops test again, but at one point it did work.  I dropped it at about the time I got the Migraphx fix complete, so I don't think I ever ran the test end to end to verify numbers; but I do know that the array shape can be converted to something Migraphx can handle.  The reason I took it out is that I thought you said you didn't want to support that feature at all if it wasn't supported in the aten op.

2024-10-23 23:13 UTC, bpickrel commented on py/torch_migraphx/fx/converters/acc_ops_converters.py
> +        # boxes2 = boxes_ref
See below; some of this code is necessary for this case if we decide to support it.  If you pass a list of tensors, you must supply default indices [0, 1, 2...].  If we put it off for the future, I can make it into a tidier looking TODO comment.

2024-10-23 23:28 UTC, shivadbhavsar commented on py/torch_migraphx/fx/converters/acc_ops_converters.py
> +        # This isn't supported because torchvision roi_align.default() doesn't support it
ok well if it works then you can add a test case. If not just leave it as a TODO to be supported later please

2024-10-23 23:38 UTC, bpickrel commented on tests/fx/converters/test_pooling_fx.py
> +def test_roialign(input, boxes, output_size, spatial_scale, sampling_ratio, aligned):
Moved to `test_torchvision_ops_fx.py`

2024-10-23 23:44 UTC, bpickrel commented on tests/dynamo/converters/test_pooling_dynamo.py
> +def test_roialign(op_alias, input, boxes, output_size, spatial_scale, sampling_ratio, aligned):
created `test_torchvision_ops_dynamo.py`

2024-10-24 00:01 UTC, bpickrel commented on tools/install_migraphx.sh
> +make -j88 install
During debugging, it did trigger substantial rebuilding each time I changed a converter.
I don't think the actual number of threads requested matters much as long as it's more than 1.

2024-10-25 14:54 UTC, TedThemistokleous commented on tools/install_migraphx.sh
> +make -j88 install
Just use -j$(nproc) instead of a defined number. That should give you what you need

2024-10-25 21:02 UTC, bpickrel commented on py/torch_migraphx/fx/converters/acc_ops_converters.py
> +        # This isn't supported because torchvision roi_align.default() doesn't support it
I'll leave it as is with a TODO after all.

2025-05-19 20:01 UTC, closed without merging